
name: Integration Tests

on:
  push:
    branches: [ develop ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  
  mocha-tests:
    runs-on: ubuntu-latest
    container: node:12.19.1-alpine
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]

    services:
      postgres:
        image: postgres:9.6.17-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: foo

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: build service
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          ./sripts/get_deps
          ./scripts/build
          ./bin/foo &
        env:
          DATABASE_NAME: foo
          DATABASE_USER: postgres
          DATABASE_HOST: '127.0.0.1'

      - name: Run Tests
        run: ./scripts/run_tests.sh

